alb_sg          = The security group id for the Application Load Balancer from README prerequisites line 5
certificate_arn = The certificate for TLS from prerequisites line 6
cluster_arn     = The AWS ARN for the ECS cluster from prerequisited line 4
container_arn   = The ARN of the ECR image of the container.
container_name  = Your preferred name for the ECS continer
ecs_sg          = The security group id for ECS from README prerequisites line 5
subnets         = [At leaast two subnets with public access from prerequisites line 3, in list form]
task_name       = Your preferred task name for the ECS service
vpc             = The VPC ID from README prerequisite line 3
